version: '3.1'

services:
    inpire-api:
        build: .
        volumes:
            - ./../../back:/var/www/html
        ports:
            - "8100:80"
        links:
            - inspire-sql
        restart: always

    inspire-sql:
        image: mysql:5.7
        volumes:
           - inspire-volume:/var/lib/mysql
        environment:
            MYSQL_DATABASE: inspire
            MYSQL_USER: Motoko
            MYSQL_PASSWORD: p455w0rd&inspire
            MYSQL_RANDOM_ROOT_PASSWORD: "78965"
        command: --default-authentication-plugin=mysql_native_password
        restart: always

    inspire-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8101:80"
        environment:
            PMA_HOST: inspire-sql
            PMA_USER: Motoko
            PMA_PASSWORD: passw0rd*

volumes:
    inspire-volume: